# Generated by Django 4.1 on 2022-08-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descrition',
            new_name='description',
        ),
    ]
