# Generated by Django 4.1 on 2022-09-02 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_imageproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(validators=[shop.validators.validate_above_zero], verbose_name='Количество товаров')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(related_name='shopping_cart', through='shop.ShoppingCartProduct', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(help_text='<span style="color:red; font-size:14px;">Если разрешение изображения слишком большое, оно будет уменьшено до 800 пикселей по большей стороне</span>', upload_to='product/', verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='shoppingcartproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartproduct',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_product_user'),
        ),
    ]
