# Generated by Django 4.1 on 2022-09-02 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shoppingcartproduct_user_shopping_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('оформлен', 'оформлен'), ('отправлен', 'отправлен'), ('закончен', 'закончен')], default='оформлен', max_length=20, verbose_name='Статус заказа')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказа')),
                ('date_sent', models.DateTimeField(blank=True, verbose_name='Дата отправки заказа')),
                ('date_completed', models.DateTimeField(blank=True, verbose_name='Дата завершения заказа')),
                ('city', models.CharField(default='Город доставки заказа', max_length=50)),
                ('address', models.CharField(default='Адрес доставки заказа', max_length=150)),
                ('shipping_method', models.CharField(choices=[('оформлен', 'оформлен'), ('отправлен', 'отправлен'), ('закончен', 'закончен')], default='почта', max_length=30, verbose_name='Способ доставки заказа')),
                ('comment', models.CharField(blank=True, max_length=250, verbose_name='Комментарии к заказу')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[shop.validators.validate_above_zero], verbose_name='Количество товаров'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1, validators=[shop.validators.validate_above_zero], verbose_name='Количество товаров')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='order', through='shop.OrderProduct', to='shop.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='orderproduct',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_order'),
        ),
    ]
