# Generated by Django 4.1 on 2022-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_alter_shoppingcartproduct_amount_orderproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('почта', 'почта'), ('СДЭК', 'СДЭК')], default='почта', max_length=30, verbose_name='Способ доставки заказа'),
        ),
    ]
