# Generated by Django 4.1 on 2022-09-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки заказа'),
        ),
    ]
